### ISSUE TITLE
Making the App Responsive and Look Awesome on Mobile Devices

### ISSUE THREAD

**Issue by BillyMassey** [lynchlcl71/splurty#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

**Comment by lynchlcl71** [comment]
Thanks for reviewing my code Billy and suggesting a way to improve it on mobile devices, I researched and added the "mobile meta tag" to the "head" section in my HTML.  I checked out the newly added code in developer tools and it is now displaying correctly on mobile devices.  Thanks again for helping me make this improvement to my code.
